@endpoint = 

@token= 

GET {{endpoint}}/hello/
Authorization: {{token}}
###

GET {{endpoint}}/hello/
###

GET {{endpoint}}/hotels/
###

GET {{endpoint}}/hotels?hotelId=epuxluiwc5b
###


POST {{endpoint}}/hotels/
Content-Type: application/json

{
    "location": "New Asia",
    "name": "New Homeland"
}
###

PUT {{endpoint}}/hotels?hotelId=8suaeo4frke
Content-Type: application/json

{
    "location": "Updated Location"
}
###

DELETE  {{endpoint}}/hotels?hotelId=vaixrgbjvmm
###
